-- Database Creation

CREATE DATABASE amazon_data_analysis;

DROP TABLE IF EXISTS shippings;
DROP TABLE IF EXISTS payments;
DROP TABLE IF EXISTS inventory;
DROP TABLE IF EXISTS order_items;
DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS sellers;
DROP TABLE IF EXISTS customers;
DROP TABLE IF EXISTS products;
DROP TABLE IF EXISTS categories;

CREATE TABLE categories(
					category_id INT PRIMARY KEY,
					category_name VARCHAR(20));

CREATE TABLE customers(
					customer_id INT PRIMARY KEY,
					first_name VARCHAR(20),
					last_name VARCHAR(20),
					state VARCHAR(20));

CREATE TABLE sellers(
				seller_id INT PRIMARY KEY,
				seller_name VARCHAR(25),
				origin VARCHAR(15));

CREATE TABLE products(
					product_id INT PRIMARY KEY,
					product_name VARCHAR(50),
					price FLOAT,
					cogs FLOAT,
					category_id INT,
					CONSTRAINT fk_product_category FOREIGN KEY (category_id) REFERENCES categories(category_id));

CREATE TABLE orders(
				order_id INT PRIMARY KEY,
				order_date DATE, 
				customer_id INT, 
				seller_id INT, 
				order_status VARCHAR(15),
				CONSTRAINT fk_orders_customers FOREIGN KEY (customer_id) REFERENCES customers(customer_id),
				CONSTRAINT fk_orders_sellers FOREIGN KEY (seller_id) REFERENCES sellers(seller_id));

CREATE TABLE order_items(
					order_item_id INT PRIMARY KEY,
					order_id INT,
					product_id INT,
					quantity INT,
					price_per_unit FLOAT,
					CONSTRAINT fk_orderitems_orders FOREIGN KEY (order_id) REFERENCES orders(order_id),
					CONSTRAINT fk_orderitems_products FOREIGN KEY (product_id) REFERENCES products(product_id));

CREATE TABLE payments(
					payment_id INT PRIMARY KEY,
					order_id INT,
					payment_date DATE,
					payment_status VARCHAR(20),
					CONSTRAINT fk_payments_orders FOREIGN KEY (order_id) REFERENCES orders(order_id));

CREATE TABLE shippings(
					shipping_id INT PRIMARY KEY,
					order_id INT,
					shipping_date DATE,
					return_date DATE,
					shipping_providers VARCHAR(15),
					delivery_status VARCHAR(15),
					CONSTRAINT fk_shippings_orders FOREIGN KEY (order_id) REFERENCES orders(order_id));

CREATE TABLE inventory(
					inventory_id INT PRIMARY KEY,
					product_id INT,
					stock INT, 
					warehouse_id INT,
					last_stock_date DATE,
					CONSTRAINT fk_inventory_products FOREIGN KEY (product_id) REFERENCES products(product_id));

SELECT * FROM categories;
SELECT * FROM customers;
SELECT * FROM inventory;
SELECT * FROM order_items;
SELECT * FROM orders;

SELECT * FROM payments;

SELECT
	DISTINCT payment_status
FROM payments;

SELECT * FROM products;
SELECT * FROM sellers;

SELECT * FROM shippings;

SELECT *
FROM shippings
WHERE return_date IS NULL;

SELECT *
FROM shippings
WHERE return_date IS NOT NULL;

SELECT *
FROM orders
WHERE order_id = 6747;

SELECT *
FROM payments
WHERE order_id = 6747;


-- Data Analysis

/*
Query the top 10 products by total sales value
Challenge: Include product name, total quantity sold and total sales value
*/

ALTER TABLE order_items
ADD COLUMN total_sales FLOAT;

UPDATE order_items
SET total_sales = quantity * price_per_unit;
SELECT * FROM order_items
ORDER BY quantity DESC;

SELECT 
	oi.product_id,
	p.product_name,
	SUM(oi.total_sales) AS total_sales,
	COUNT(o.order_id) AS total_orders
FROM orders AS o
JOIN order_items AS oi
ON o.order_id = oi.order_id
JOIN products AS p
ON p.product_id = oi.product_id
GROUP BY 1, 2
ORDER BY 3 DESC
LIMIT 10;

/*
Calculate total revenue generated by each product category
Include the percentage contribution of each category to total revenue
*/

SELECT 
	p.category_id,
	c.category_name,
	SUM(oi.total_sales) AS total_sales,
	SUM(oi.total_sales) / (SELECT SUM(total_sales) FROM order_items) * 100 AS percentage_contribution
FROM order_items AS oi
JOIN products AS p
ON p.product_id = oi.product_id
LEFT JOIN categories AS c 
ON c.category_id = p.category_id
GROUP BY 1, 2
ORDER BY 3 DESC;

/*
Compute the average order value for each customer
Include customers with more than 5 orders
*/

SELECT 
	c.customer_id,
	CONCAT(c.first_name, ' ', c.last_name) AS full_name,
	SUM(total_sales) / COUNT(o.order_id) AS average_order_value,
	COUNT(o.order_id) AS total_orders
FROM orders AS o
JOIN customers AS c
ON c.customer_id = o.customer_id
JOIN order_items AS oi
ON oi.order_id = o.order_id
GROUP BY 1, 2
HAVING COUNT(o.order_id) > 5;

/*
Query monthly total sales over the past 3 years
Display the sales trend, grouping by month; return current and last month sales
*/

SELECT 
	year,
	month,
	total_sales AS current_month_sales,
	LAG(total_sales, 1) OVER(ORDER BY year, month) AS last_month_sales
FROM
	(SELECT 
		EXTRACT(MONTH FROM o.order_date) AS month,
		EXTRACT(YEAR FROM o.order_date) AS year,
		ROUND(SUM(oi.total_sales::numeric), 2) AS total_sales
	FROM orders AS o
	JOIN order_items AS oi
	ON oi.order_id = o.order_id
	WHERE order_date >= CURRENT_DATE - INTERVAL '3 year'
	GROUP BY 1, 2
	ORDER BY year, month) AS t1

/*
Find customers who have registered but have never placed an order
List customer details and the time since their registration
*/

SELECT *
FROM customers
WHERE customer_id NOT IN (SELECT 
							DISTINCT customer_id
						  FROM orders);

SELECT *
FROM customers AS c
LEFT JOIN orders AS o
ON o.customer_id = c.customer_id
WHERE o.customer_id IS NULL;

/*
Identify the lowest selling product category for each state
Include the total sales for the lowest selling category in each state
*/

WITH ranking_table
AS
	(SELECT 
		c.state,
		ct.category_name,
		SUM(oi.total_sales) AS total_sales,
		RANK() OVER(PARTITION BY c.state ORDER BY SUM(oi.total_sales) ASC) AS rank
	FROM orders AS o
	JOIN customers AS c
	ON o.customer_id = c.customer_id
	JOIN order_items AS oi
	ON o.order_id = oi.order_id
	JOIN products AS p
	ON oi.product_id = p.product_id
	JOIN categories AS ct
	ON ct.category_id = p.category_id
	GROUP BY 1, 2)
SELECT * FROM ranking_table
WHERE rank = 1;

/*
Calculate the total value of orders placed by each customer over their lifetime
Rank customers based on their lifetime value
*/

SELECT
	c.customer_id,
	CONCAT(c.first_name, ' ', c.last_name) AS full_name,
	SUM(total_sales) AS customer_lifetime_value,
	DENSE_RANK() OVER(ORDER BY SUM(total_sales) DESC) AS customer_ranking
FROM orders AS o
JOIN customers AS c
ON c.customer_id = o.customer_id
JOIN order_items AS oi
ON oi.order_id = o.order_id
GROUP BY 1, 2;

/*
Query products with stock levels below a certain threshold (e.g. < 10 units)
Include last restock date and warehouse information
*/

SELECT
	i.inventory_id,
	p.product_name,
	i.stock AS current_stock_remaining,
	i.last_stock_date,
	i.warehouse_id
FROM inventory AS i
JOIN products AS p
ON p.product_id = i.product_id
WHERE stock < 10;

/*
Identify orders where the shipping date is later than 3 days after the order date
Include customer, order details and delivery provider
*/

SELECT 
	c.*,
	o.*,
	s.shipping_providers,
	s.shipping_date - o.order_date AS elapsed_shipping_time
FROM orders AS o
JOIN customers AS c
ON c.customer_id = o.customer_id
JOIN shippings AS s
ON o.order_id = s.order_id
WHERE s.shipping_date - o.order_date > 3;

/*
Calculate the percentage of successful payments across all orders
Include breakdowns by payment status (e.g. failed, pending)
*/

SELECT 
	p.payment_status,
	COUNT(*) AS payment_status_count,
	COUNT(*) / (SELECT COUNT(*) FROM payments)::numeric * 100 AS payment_status_percentage
FROM orders AS o
JOIN payments AS p
ON o.order_id = p.order_id
GROUP BY 1;

/*
Find the top 5 sellers based on total sales value
Include both successful and failed orders; display their percentage of successful orders
*/

WITH top_sellers
AS
	(SELECT 
		s.seller_id, 
		s.seller_name,
		SUM(oi.total_sales) AS total_sales
	FROM orders AS o
	JOIN sellers AS s
	ON o.seller_id = s.seller_id
	JOIN order_items AS oi
	ON oi.order_id = o.order_id
	GROUP BY 1, 2
	ORDER BY 3 DESC
	LIMIT 5),
seller_reports
AS
	(SELECT 
		o.seller_id,
		ts.seller_name,
		o.order_status,
		COUNT(*) AS total_orders
	FROM orders AS o
	JOIN top_sellers AS ts
	ON ts.seller_id = o.seller_id
	WHERE 
		o.order_status NOT IN ('Inprogress', 'Returned')
	GROUP BY 1, 2, 3)
SELECT 
	seller_id,
	seller_name,
	SUM(CASE WHEN order_status = 'Completed' THEN total_orders ELSE 0 END) AS completed_orders,
	SUM(CASE WHEN order_status = 'Cancelled' THEN total_orders ELSE 0 END) AS cancelled_orders,
	SUM(total_orders) AS total_orders,
	SUM(CASE WHEN order_status = 'Completed' THEN total_orders ELSE 0 END)::numeric / SUM(total_orders)::numeric * 100 AS percentage_of_successful_orders
FROM seller_reports
GROUP BY 1, 2;

/*
Calculate the profit margin for each product (price minus cost of goods sold)
Rank products by their profit margin, showing highest to lowest
*/

SELECT 
	product_id,
	product_name,
	profit_margin,
	DENSE_RANK() OVER(ORDER BY profit_margin DESC) AS product_ranking
FROM
	(SELECT 
		p.product_id,
		p.product_name,
		SUM(total_sales - (p.cogs * oi.quantity)) AS profit,
		SUM(total_sales - (p.cogs * oi.quantity)) / sum(total_sales) * 100 AS profit_margin
	FROM order_items AS oi
	JOIN products AS p
	ON oi.product_id = p.product_id
	GROUP BY 1, 2) AS t1

/*
Query the top 10 products by the number of returns
Display the return rate as a percentage of total units sold for each product
*/

SELECT
	p.product_id,
	p.product_name,
	COUNT(*) AS total_units_sold,
	SUM(CASE WHEN o.order_status = 'Returned' THEN 1 ELSE 0 END) AS total_returned,
	SUM(CASE WHEN o.order_status = 'Returned' THEN 1 ELSE 0 END)::numeric / COUNT(*)::numeric * 100 AS return_percentage
FROM order_items AS oi
JOIN products AS p
ON oi.product_id = p.product_id
JOIN orders AS o
ON o.order_id = oi.order_id
GROUP BY 1, 2
ORDER BY 5 DESC
LIMIT 10;

/*
Identify sellers who haven’t made any sales in the last 2 years
Show the last sale date and total sales from those sellers
*/

WITH sellers_cte1
AS
	(SELECT * FROM sellers
	 WHERE seller_id NOT IN (SELECT seller_id FROM orders 
							 WHERE order_date >= CURRENT_DATE - INTERVAL '2 year'))
SELECT 
	o.seller_id,
	MAX(o.order_date) AS last_sale_date,
	MAX(oi.total_sales) AS last_sale_amount
FROM orders AS o
JOIN sellers_cte1 AS cte1
ON cte1.seller_id = o.seller_id
JOIN order_items AS oi
ON o.order_id = oi.order_id
GROUP BY 1;
	
/*
Categorise customers based on returns; if more than 5, categorise as returning
List customer identification, name, total orders and total returns
*/

SELECT 
	full_name AS customer,
	total_orders,
	total_returned,
	CASE WHEN total_returned > 5 THEN 'Returning Customer' ELSE 'New Customer' END AS customer_category
FROM
	(SELECT 
		CONCAT(c.first_name, ' ', c.last_name) AS full_name,
		COUNT(o.order_id) AS total_orders,
		SUM(CASE WHEN o.order_status = 'Returned' THEN 1 ELSE 0 END) AS total_returned
	FROM orders AS o
	JOIN customers AS c
	ON c.customer_id = o.customer_id
	JOIN order_items AS oi
	ON oi.order_id = o.order_id
	GROUP BY 1) AS t1

/*
Identify the top 5 customers with the highest number of orders for each state
Include the number of orders and total sales for each customer
*/

SELECT * 
FROM
	(SELECT 
		c.state, 
		CONCAT(c.first_name, ' ', c.last_name) AS customer,
		COUNT(o.order_id) AS total_orders,
		SUM(total_sales) AS total_sales,
		DENSE_RANK() OVER(PARTITION BY c.state ORDER BY COUNT(o.order_id) DESC) AS rank
	FROM orders AS o
	JOIN order_items AS oi
	ON o.order_id = oi.order_id
	JOIN customers AS c
	ON c.customer_id = o.customer_id
	GROUP BY 1, 2) AS t1
WHERE rank <= 5

/*
Calculate the total revenue handled by each shipping provider
Include the total number of orders handled and the average delivery time for each provider
*/

SELECT 
	s.shipping_providers,
	COUNT(o.order_id) AS orders_handled,
	SUM(oi.total_sales) AS total_sales, 
	COALESCE(AVG(s.return_date - s.shipping_date), 0) AS average_days
FROM orders AS o
JOIN order_items AS oi
ON oi.order_id = o.order_id
JOIN shippings AS s
ON s.order_id = o.order_id
GROUP BY 1;

/*
Find the top 10 products with highest decreasing revenue ratio in terms of 2022 and 2023
Return product_id, product_name, category_name, 2022 revenue and 2023 revenue decrease ratio 
Decrease ratio = (cs - ls) / ls * 100 (cs = current_year, ls = last_year)
*/

WITH sales_2022
AS
	(SELECT 
		p.product_id,
		p.product_name,
		SUM(oi.total_sales) AS revenue
	FROM orders AS o
	JOIN order_items AS oi
	ON oi.order_id = o.order_id
	JOIN products AS p
	ON p.product_id = oi.product_id
	WHERE EXTRACT(YEAR FROM o.order_date) = 2022
	GROUP BY 1, 2),
sales_2023
AS
	(SELECT 
		p.product_id,
		p.product_name,
		SUM(oi.total_sales) AS revenue
	FROM orders AS o
	JOIN order_items AS oi
	ON oi.order_id = o.order_id
	JOIN products AS p
	ON p.product_id = oi.product_id
	WHERE EXTRACT(YEAR FROM o.order_date) = 2023
	GROUP BY 1, 2)
SELECT 
	s23.product_id,
	s22.revenue AS revenue_2022,
	s23.revenue AS revenue_2023,
	s22.revenue - s23.revenue AS revenue_difference,
	ROUND((s23.revenue - s22.revenue)::numeric / (s22.revenue)::numeric * 100, 2) AS revenue_decrease_ratio
FROM sales_2022 AS s22
JOIN sales_2023 AS s23
ON s22.product_id = s23.product_id
WHERE 
	s22.revenue > s23.revenue
	AND 
	ROUND((s23.revenue - s22.revenue)::numeric / (s22.revenue)::numeric * 100, 2) <> 0.00
ORDER BY 5 DESC
LIMIT 10;


-- Stored Procedure Implementation

/*
Create a function that reduces quantity from inventory table as soon as the product is sold
The function should update stock in inventory table based on product and quantity purchased
*/

SELECT * FROM products;
SELECT * FROM inventory;

-- product_id - 1, product_name - Apple AirPods 3rd Gen, stock - 55
-- product_id - 2, product_name - Apple AirPods Max, stock - 39 

SELECT * FROM orders;
SELECT * FROM order_items;

CREATE OR REPLACE PROCEDURE add_sales(
									p_order_id INT,
									p_customer_id INT,
									p_seller_id INT,
									p_order_item_id INT,
									p_product_id INT,
									p_quantity INT)

LANGUAGE plpgsql
AS $$

DECLARE

v_count INT;
v_price FLOAT;
v_product VARCHAR(50);

BEGIN

	SELECT 
		price, product_name 
		INTO 
		v_price, v_product
	FROM products 
	WHERE product_id = p_product_id;

	SELECT 
		COUNT(*)
		INTO 
		v_count
	FROM inventory
	WHERE 
		product_id = p_product_id
		AND 
		stock >= p_quantity;

	IF v_count > 0 THEN 
	
		INSERT INTO orders(order_id, order_date, customer_id, seller_id)
		VALUES(p_order_id, CURRENT_DATE, p_customer_id, p_seller_id);
		
		INSERT INTO order_items(order_item_id, order_id, product_id, quantity, price_per_unit, total_sales)
		VALUES(p_order_item_id, p_order_id, p_product_id, p_quantity, v_price, v_price * p_quantity);

		UPDATE inventory
		SET stock = stock - p_quantity
		WHERE product_id = p_product_id;

		RAISE NOTICE 'Thank you. Product sale for % has been added and inventory is up to date.', v_product;

	ELSE 
	
		RAISE NOTICE 'Thank you for your information. The product % is not available.', v_product;

	END IF;

END;
$$

CALL add_sales(25005, 2, 5, 25004, 1, 14);
